export const DataSi = [
    {
        id: 1,
        nama: 'Dhita Khairunnisa',
        umur: '17',
        kelas: 'XI PKM 1',
        jabatan: 'Ketua PMR',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/KjrbLkvF/Desain-tanpa-judul-1.png',
      },
      {
        id: 2,
        nama: 'Aisy Marsa Fadhlillah Prasetyo',
        umur: '17',
        kelas: 'XI RPL 3',
        jabatan: 'Wakil Ketua PMR',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/qRCrQDQk/Desain-tanpa-judul-2.png',
      },
      {
        id: 3,
        nama: 'Salwa Khalilah Amorita',
        umur: '16',
        kelas: 'XI PKM 1',
        jabatan: 'Sekretaris 1',
        bidang: 'PP',
        photoUrl: 'https://i.postimg.cc/nzV7D71Y/Desain-tanpa-judul-3.png',
      },
      {
        id: 4,
        nama: 'Berliana Dian Savira',
        umur: '16',
        kelas: 'XI PKM 1',
        jabatan: 'Sekretaris 2',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/XY08Qscn/Desain-tanpa-judul-6.png',
      },
      {
        id: 5,
        nama: 'Mochammad Hafidz Nugraha',
        umur: '16',
        kelas: 'XI RPL 1',
        jabatan: 'Bendahara 1',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/vmCDtNfz/Desain-tanpa-judul-10.png',
      },
      {
        id: 6,
        nama: 'Juwita Bunga Ramadyna',
        umur: '16',
        kelas: 'XI RPL 1',
        jabatan: 'Bendahara 2',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/qBw4kFq5/Desain-tanpa-judul-11.png',
      },
]