import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic';

const Navbar = dynamic(
  () => import("../../components/Navbar/Navbar").then((mod) => mod.Navbar),
  {
    ssr: false,
  }
);
const Anggota13Comp = dynamic(
  () => import("../../components/Isi Anggota/Anggota13Comp").then((mod) => mod.AnggotaComp),
  {
    ssr: false,
  }
);
const Anggota14Comp = dynamic(
  () => import("../../components/Isi Anggota/Anggota14Comp").then((mod) => mod.AnggotaComp),
  {
    ssr: false,
  }
);

function anggotaan() {
  return (
    <>
      <Head>
        <title>Anggota</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pmrwira.png" />
      </Head>
      <div>
        <Navbar />
        <Anggota13Comp />
        <Anggota14Comp />
      </div>
    </>
  )
}

export default anggotaan
