import React from 'react'
import Head from 'next/head';
import dynamic from 'next/dynamic';

const Navbar = dynamic(
  () => import("../../components/Navbar/Navbar").then((mod) => mod.Navbar),
  {
    ssr: false,
  }
);
const SsComp = dynamic(
  () => import("../../components/Struktur Sekbid/SsComp").then((mod) => mod.SsComp),
  {
    ssr: false,
  }
);

function struktursekbid() {
  return (
      <>
      <Head>
        <title>Struktur Sekbid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pmrwira.png" />
      </Head>
      <div>
        <Navbar />
        <SsComp />
      </div>
    </>

  )
}

export default struktursekbid;
