export const DataSs = [
    {
        id: 1,
        nama: 'Nasywa Putri Aulia',
        umur: '17',
        kelas: 'XI RPL 1',
        jabatan: 'Koor Sekbid Acara',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/1t5S1593/Desain-tanpa-judul-7.png',
      },
      {
        id: 2,
        nama: 'Salwa Shafa',
        umur: '16',
        kelas: 'XI DPIB 1',
        jabatan: 'Koor Sekbid Humas',
        bidang: 'PP',
        photoUrl: 'https://i.postimg.cc/c4MNCnrL/Desain-tanpa-judul-9.png',
      },
      {
        id: 3,
        nama: 'Alvia Nur Adhani',
        umur: '17',
        kelas: 'XI PKM 1',
        jabatan: 'Koor Sekbid Logistk',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/HLWWdtzm/Desain-tanpa-judul-8.png',
      },
      {
        id: 4,
        nama: 'Adinda lestari ',
        umur: '16',
        kelas: 'XI PKM 3',
        jabatan: 'Koor Sekbid Latihan',
        bidang: 'PK',
        photoUrl: 'https://i.postimg.cc/HLgvFZpY/Desain-tanpa-judul-4.png',
      },
      {
        id: 5,
        nama: 'Zahrah Nailal Husna',
        umur: '16',
        kelas: 'XI PKM 1',
        jabatan: 'Koor Sekbid Dana Usaha',
        bidang: 'PP',
        photoUrl: 'https://i.postimg.cc/VvYC8w3s/Desain-tanpa-judul.png',
      },
      {
        id: 6,
        nama: 'Nadia Faradilla',
        umur: '16',
        kelas: 'XI PKM 1',
        jabatan: 'Koor Sekbid Kesehatan',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/mrP3X79L/Desain-tanpa-judul-5.png',
      },
      {
        id: 7,
        nama: 'Hamdan Fahruroji',
        umur: '17',
        kelas: 'XI TPTU 2',
        jabatan: 'Koor Sekbid Keamanan',
        bidang: 'Tandu',
        photoUrl: 'https://i.postimg.cc/25T6Zty3/Desain-tanpa-judul-12.png',
      },
]